export const ELEMENT_DATA = [
  {
    id: 1,
    carrera_id: 1,
    nombre: 'Juan',
    email: 'Juan.Perez@gmail.com',
    apellido: 'Perez',
    fechaNac: '01/01/2000',
    edad: 21,
    carrera: 'Ingeniería en Sistemas',
    semestre: 5,
    promedio: 8.5,
  },
  {
    id: 2,
    carrera_id: 2,
    nombre: 'Maria',
    email: 'Maria.Gomez@gmail.com',
    apellido: 'Gomez',
    fechaNac: '05/12/1999',
    edad: 22,
    carrera: 'Ingeniería Industrial',
    semestre: 6,
    promedio: 7.8,
  },
  {
    id: 3,
    carrera_id: 3,
    nombre: 'Pedro',
    email: 'Pedro.Lopez@gmail.com',
    apellido: 'Lopez',
    fechaNac: '10/07/2001',
    edad: 20,
    carrera: 'Licenciatura en Administración',
    semestre: 4,
    promedio: 9.2,
  },
  {
    id: 4,
    carrera_id: 1,
    nombre: 'Ana',
    email: 'Ana.Martinez@gmail.com',
    apellido: 'Martinez',
    fechaNac: '15/03/1998',
    edad: 23,
    carrera: 'Ingeniería en Sistemas',
    semestre: 8,
    promedio: 9.0,
  },
  {
    id: 5,
    carrera_id: 2,
    nombre: 'Carlos',
    email: 'Carlos.Rodriguez@gmail.com',
    apellido: 'Rodriguez',
    fechaNac: '20/09/2002',
    edad: 19,
    carrera: 'Ingeniería Industrial',
    semestre: 3,
    promedio: 6.5,
  },
  {
    id: 7,
    carrera_id: 2,
    nombre: 'Luis',
    email: 'Luis.Hernandez@gmail.com',
    apellido: 'Hernandez',
    fechaNac: '03/09/1999',
    edad: 22,
    carrera: 'Ingeniería Industrial',
    semestre: 7,
    promedio: 7.5,
  },
  {
    id: 8,
    carrera_id: 3,
    nombre: 'Sofia',
    email: 'Sofia.Lopez@gmail.com',
    apellido: 'Lopez',
    fechaNac: '08/11/2001',
    edad: 20,
    carrera: 'Licenciatura en Administración',
    semestre: 5,
    promedio: 9.0,
  },
  {
    id: 6,
    carrera_id: 1,
    nombre: 'Laura',
    email: 'Laura.Gonzalez@gmail.com',
    apellido: 'Gonzalez',
    fechaNac: '12/06/2000',
    edad: 21,
    carrera: 'Ingeniería en Sistemas',
    semestre: 6,
    promedio: 8.0,
  },
  {
    id: 9,
    carrera_id: 1,
    nombre: 'Daniel',
    email: 'Daniel.Garcia@gmail.com',
    apellido: 'Garcia',
    fechaNac: '17/02/1998',
    edad: 23,
    carrera: 'Ingeniería en Sistemas',
    semestre: 9,
    promedio: 8.7,
  },
  {
    id: 10,
    carrera_id: 2,
    nombre: 'Fernanda',
    email: 'Fernanda.Martinez@gmail.com',
    apellido: 'Martinez',
    fechaNac: '22/07/2002',
    edad: 19,
    carrera: 'Ingeniería Industrial',
    semestre: 4,
    promedio: 7.2,
  },
  {
    id: 11,
    carrera_id: 1,
    nombre: 'Diego',
    email: 'Diego.Rodriguez@gmail.com',
    apellido: 'Rodriguez',
    fechaNac: '27/12/1997',
    edad: 24,
    carrera: 'Ingeniería en Sistemas',
    semestre: 10,
    promedio: 9.5,
  },
  {
    id: 12,
    carrera_id: 2,
    nombre: 'Valeria',
    email: 'Valeria.Perez@gmail.com',
    apellido: 'Perez',
    fechaNac: '02/03/2001',
    edad: 20,
    carrera: 'Ingeniería Industrial',
    semestre: 6,
    promedio: 8.3,
  },
  {
    id: 13,
    carrera_id: 3,
    nombre: 'Javier',
    email: 'Javier.Gomez@gmail.com',
    apellido: 'Gomez',
    fechaNac: '07/08/1999',
    edad: 22,
    carrera: 'Licenciatura en Administración',
    semestre: 5,
    promedio: 7.0,
  },
  {
    id: 14,
    carrera_id: 1,
    nombre: 'Carolina',
    email: 'Carolina.Lopez@gmail.com',
    apellido: 'Lopez',
    fechaNac: '16/01/2003',
    edad: 19,
    carrera: 'Ingeniería en Sistemas',
    semestre: 3,
    promedio: 6.8,
  },
  {
    id: 15,
    carrera_id: 2,
    nombre: 'Ricardo',
    email: 'Ricardo.Martinez@gmail.com',
    apellido: 'Martinez',
    fechaNac: '21/06/1998',
    edad: 23,
    carrera: 'Ingeniería Industrial',
    semestre: 8,
    promedio: 9.1,
  },
];
