export * from './users.interface';
export * from './students.interface';
export * from './schedule.interface';
export * from './teacher.interface';
export * from './courses.interface';
export * from './classroom.interface';
export * from './attendance.interface';
export * from './grades.interface';
export * from './roles.interface';